#!/usr/bin/env python
'''
Copyright (c) 2017, Jesper Derehag
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Short description:
   pre-commit hook, essentially runs all unittests and flake8
'''
from __future__ import print_function

import os
import subprocess


def main():
    print('Running pre-commit tests')
    print('..checking patch...')

    cmd = 'git diff --cached --name-only --diff-filter=ACMRX'
    modified_files = subprocess.check_output(cmd.split()).split()

    cmd = 'python ' + os.path.join('tools', 'check_patch.py')
    if subprocess.call(cmd.split() + modified_files) != 0:
        exit(-1)

    print('..Running unittests...')
    cmd = 'python ' + os.path.join('tools', 'run_tests.py') + ' -q'
    if subprocess.call(cmd.split()) != 0:
        exit(-1)


if __name__ == '__main__':
    main()
